name: miscelaneos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  sensors_plus: ^6.0.1
  share_plus: ^10.0.2

dev_dependencies:
  change_app_package_name: ^1.3.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
