name: miscelaneos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  flutter_riverpod: ^2.5.1
  geolocator: ^13.0.1
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  google_mobile_ads: ^5.1.0
  isar: ^3.1.0+1
  local_auth: ^2.3.0
  permission_handler: ^11.3.1
  quick_actions: ^1.0.7
  sensors_plus: ^6.0.1
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  workmanager: ^0.5.2

dev_dependencies:
  change_app_package_name: ^1.3.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
